"""
Progress routes — weight trend analysis and forecast generation.
"""
from fastapi import APIRouter
from tools.mongodb_tools import get_recent_logs, get_latest_forecast, get_user
import logging

router = APIRouter()
logger = logging.getLogger(__name__)


@router.get("/summary")
async def get_progress_summary(user_id: str):
    """
    Full progress summary — weight trend + log counts.
    Triggers ProgressAnalysisAgent if enough data exists.
    """
    from agents.runner import run_agent
    from agents.progress_agent import progress_agent

    weights = await get_recent_logs(user_id, "weight", limit=30)
    workouts = await get_recent_logs(user_id, "workout", limit=30)
    food_logs = await get_recent_logs(user_id, "food", limit=30)

    weight_values = [
        r["data"]["value_kg"]
        for r in weights
        if "data" in r and "value_kg" in r["data"]
    ]

    trend_kg = 0.0
    weekly_rate = 0.0
    if len(weight_values) >= 2:
        # weight_values[0] = newest (desc sort), weight_values[-1] = oldest
        total_change = weight_values[0] - weight_values[-1]
        trend_kg = round(total_change, 2)
        weekly_rate = round(total_change / max(len(weight_values) - 1, 1) * 7, 2)

    # Run ProgressAnalysisAgent if we have enough data
    agent_insight = ""
    if len(weight_values) >= 3:
        try:
            result = await run_agent(
                progress_agent,
                user_id=user_id,
                message=f"Analyze progress for user_id={user_id}. Generate forecast and insights.",
            )
            agent_insight = result.get("response", "")
            logger.info(f"ProgressAnalysisAgent ran for {user_id}: tools={result.get('tools_used', [])}")
        except Exception as e:
            logger.error(f"ProgressAnalysisAgent error: {e}")

    return {
        "weight_trend_kg": trend_kg,
        "weekly_rate_kg": weekly_rate,
        "weight_entries": len(weight_values),
        "latest_weight": weight_values[-1] if weight_values else None,
        "first_weight": weight_values[0] if weight_values else None,
        "workout_count_30d": len(workouts),
        "food_log_count_30d": len(food_logs),
        "agent_insight": agent_insight,
    }


@router.get("/forecast")
async def get_forecast(user_id: str):
    """Latest forecast — generated by ForecastingAgent."""
    from agents.runner import run_agent
    from agents.forecasting_agent import forecasting_agent

    forecast = await get_latest_forecast(user_id)

    # If no forecast exists but we have weight data, generate one now
    if not forecast:
        weights = await get_recent_logs(user_id, "weight", limit=14)
        if len(weights) >= 3:
            try:
                result = await run_agent(
                    forecasting_agent,
                    user_id=user_id,
                    message=f"Generate 30-day forecast for user_id={user_id}.",
                )
                forecast = await get_latest_forecast(user_id)
                logger.info(f"ForecastingAgent ran for {user_id}: tools={result.get('tools_used', [])}")
            except Exception as e:
                logger.error(f"ForecastingAgent error: {e}")

    return forecast or {
        "user_id": user_id,
        "scenarios": {"optimistic": [], "realistic": [], "pessimistic": []},
        "message": "Log at least 3 weight entries to generate a forecast.",
    }
