"""
User routes — onboarding and profile.
"""
from fastapi import APIRouter, HTTPException
from models.schemas import OnboardingRequest
from tools.mongodb_tools import create_user, get_user, award_xp, update_streak
import logging

router = APIRouter()
logger = logging.getLogger(__name__)


@router.post("/onboard")
async def onboard_user(request: OnboardingRequest):
    """
    Onboard a new user:
    1. Save profile to MongoDB
    2. NutritionAgent generates nutrition plan
    3. WorkoutAgent generates workout plan
    4. Award welcome XP
    """
    from agents.runner import run_agent
    from agents.nutrition_agent import nutrition_agent
    from agents.workout_agent import workout_agent

    # 1. Save user
    user_data = {
        "name": request.name,
        "email": request.email,
        "profile": request.profile.model_dump(),
        "goals": request.goals.model_dump(),
    }
    user_id = await create_user(user_data)
    logger.info(f"User created: {user_id}")

    # 2. NutritionAgent generates initial plan
    profile = request.profile
    goals = request.goals

    # Calculate rough TDEE for context
    bmr = (10 * profile.weight_kg) + (6.25 * profile.height_cm) - (5 * profile.age) + (5 if profile.sex == "male" else -161)
    activity_multipliers = {"sedentary": 1.2, "light": 1.375, "moderate": 1.55, "active": 1.725, "very_active": 1.9}
    tdee = bmr * activity_multipliers.get(profile.activity_level, 1.55)
    if goals.type == "weight_loss":
        daily_calories = int(tdee - 400)
    elif goals.type == "weight_gain":
        daily_calories = int(tdee + 300)
    else:
        daily_calories = int(tdee)

    nutrition_prompt = f"""
Generate an initial nutrition plan for a new user and save it to MongoDB.

user_id: {user_id}
Name: {request.name}
Age: {profile.age}, Sex: {profile.sex}
Weight: {profile.weight_kg}kg, Height: {profile.height_cm}cm
Activity level: {profile.activity_level}
Goal: {goals.type}
Target weight: {goals.target_weight_kg or 'not specified'}kg
Estimated daily calories needed: {daily_calories} kcal

Call create_plan with:
- user_id: "{user_id}"
- type: "nutrition"
- version: 1
- created_by_agent: "NutritionAgent"
- reason_for_update: "Initial plan generated from user profile"
- content: {{
    "daily_calories": {daily_calories},
    "macros": {{"protein_g": {int(daily_calories * 0.3 / 4)}, "carbs_g": {int(daily_calories * 0.4 / 4)}, "fat_g": {int(daily_calories * 0.3 / 9)}}},
    "meal_schedule": [
      {{"meal": "Breakfast", "calories": {int(daily_calories * 0.25)}, "time": "8:00 AM", "example": "Oats + eggs + fruit"}},
      {{"meal": "Lunch", "calories": {int(daily_calories * 0.35)}, "time": "1:00 PM", "example": "Chicken rice bowl + salad"}},
      {{"meal": "Dinner", "calories": {int(daily_calories * 0.30)}, "time": "7:00 PM", "example": "Salmon + vegetables + quinoa"}},
      {{"meal": "Snack", "calories": {int(daily_calories * 0.10)}, "time": "4:00 PM", "example": "Greek yogurt + almonds"}}
    ]
  }}

Then call log_agent_decision with your reasoning.
"""
    nutrition_result = await run_agent(nutrition_agent, user_id=user_id, message=nutrition_prompt)
    logger.info(f"NutritionAgent completed for {user_id}: tools={nutrition_result['tools_used']}")

    # 3. WorkoutAgent generates initial plan
    workout_prompt = f"""
Generate an initial workout plan for a new user and save it to MongoDB.

user_id: {user_id}
Goal: {goals.type}
Weekly workout days: {goals.weekly_workout_days}
Activity level: {profile.activity_level}

Call create_plan with:
- user_id: "{user_id}"
- type: "workout"
- version: 1
- created_by_agent: "WorkoutAgent"
- reason_for_update: "Initial plan generated from user profile"
- content with a weekly_schedule for {goals.weekly_workout_days} workout days + rest days.
  Each day: {{"day": "Monday", "type": "Strength", "focus": "Push (Chest/Shoulders/Triceps)", "duration_min": 45}}
  Types: Strength, Cardio, Rest

Then call log_agent_decision.
"""
    workout_result = await run_agent(workout_agent, user_id=user_id, message=workout_prompt)
    logger.info(f"WorkoutAgent completed for {user_id}: tools={workout_result['tools_used']}")

    # 4. Welcome XP
    await award_xp(user_id=user_id, xp_amount=100, reason="Welcome to HealthOS!")
    await update_streak(user_id=user_id)

    return {
        "user_id": user_id,
        "name": request.name,
        "message": f"Welcome {request.name}! Your personalized plans have been generated by AI agents.",
        "agents_used": ["NutritionAgent", "WorkoutAgent"],
        "nutrition_response": nutrition_result.get("response", ""),
        "workout_response": workout_result.get("response", ""),
        "xp_awarded": 100,
    }


@router.get("/{user_id}")
async def get_user_profile(user_id: str):
    user = await get_user(user_id)
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    return user
