/**
 * System / For Judges page
 * Explicitly maps to hackathon judging criteria.
 * Accessible via /system from sidebar.
 */
import { useEffect, useState } from 'react'
import { healthCheck } from '../api/client'

const JUDGING_CRITERIA = [
  {
    score: '25pts',
    title: 'Technological Implementation',
    color: 'border-purple-500/40 bg-purple-500/5',
    titleColor: 'text-purple-400',
    items: [
      { label: 'Google Cloud AI', value: 'Gemini 2.5 Flash via Vertex AI', icon: '🧠' },
      { label: 'Agent Framework', value: 'Google Cloud ADK (google-adk 1.34+)', icon: '⚙️' },
      { label: 'Partner MCP', value: 'MongoDB Atlas — all state persisted via tool calls', icon: '🍃' },
      { label: 'Agent Behavior', value: '6 specialized agents with real tool use, planning & memory', icon: '🤖' },
    ],
  },
  {
    score: '25pts',
    title: 'Design',
    color: 'border-blue-500/40 bg-blue-500/5',
    titleColor: 'text-blue-400',
    items: [
      { label: 'UX', value: 'Dark-mode health dashboard, mobile-responsive', icon: '🎨' },
      { label: 'Demo Flow', value: 'One-click demo account loads full data instantly', icon: '▶️' },
      { label: 'Agent Visibility', value: 'Live Agent Activity panel shows every decision', icon: '📡' },
      { label: 'Data Viz', value: 'Recharts weight trend, forecast scenarios, XP bar', icon: '📊' },
    ],
  },
  {
    score: '25pts',
    title: 'Potential Impact',
    color: 'border-green-500/40 bg-green-500/5',
    titleColor: 'text-green-400',
    items: [
      { label: 'Problem', value: 'Generic fitness apps don\'t adapt — ours does, autonomously', icon: '🎯' },
      { label: 'Real-world use', value: 'Logs meals/workouts/sleep → agents update plans in <3s', icon: '⚡' },
      { label: 'Scalability', value: 'MongoDB Atlas scales to millions of users; agents are stateless', icon: '📈' },
      { label: 'Personalization', value: 'Every plan is generated by Gemini from your actual data', icon: '👤' },
    ],
  },
  {
    score: '25pts',
    title: 'Quality of Idea',
    color: 'border-yellow-500/40 bg-yellow-500/5',
    titleColor: 'text-yellow-400',
    items: [
      { label: 'Novelty', value: 'First AI health OS with multi-agent plan adaptation', icon: '✨' },
      { label: 'Agentic (not chatbot)', value: 'Agents plan → execute → store → notify autonomously', icon: '🧩' },
      { label: 'MongoDB as memory', value: 'Agent decisions, plans, logs all persist in Atlas collections', icon: '💾' },
      { label: 'Wow factor', value: 'Log poor sleep → RecoveryAgent reduces workout intensity in real-time', icon: '🔥' },
    ],
  },
]

const AGENTS = [
  { name: 'OrchestratorAgent', color: 'text-purple-400', role: 'Routes user intent to specialist agents', tools: ['classify_intent', 'route_to_agent'], trigger: 'Every chat message' },
  { name: 'NutritionAgent',    color: 'text-green-400',  role: 'Analyzes food logs, adapts calorie targets', tools: ['get_active_plan', 'create_plan', 'get_daily_nutrition_totals', 'log_agent_decision', 'award_xp'], trigger: 'Food log' },
  { name: 'WorkoutAgent',      color: 'text-blue-400',   role: 'Tracks workout consistency, adjusts intensity', tools: ['get_active_plan', 'create_plan', 'get_recent_logs', 'log_agent_decision', 'award_xp'], trigger: 'Workout log' },
  { name: 'RecoveryAgent',     color: 'text-yellow-400', role: 'Analyzes sleep, reduces workout intensity if needed', tools: ['get_recent_logs', 'get_active_plan', 'create_plan', 'log_agent_decision'], trigger: 'Sleep log' },
  { name: 'ProgressAnalysisAgent', color: 'text-pink-400', role: 'Weight trend analysis, goal % tracking', tools: ['get_user', 'get_recent_logs', 'save_forecast', 'log_agent_decision'], trigger: 'Weight log' },
  { name: 'ForecastingAgent',  color: 'text-cyan-400',   role: '30-day weight forecast, 3 scenarios', tools: ['get_user', 'get_recent_logs', 'save_forecast', 'log_agent_decision'], trigger: 'Progress check' },
]

const MONGODB_COLLECTIONS = [
  { name: 'users',           desc: 'Profile, goals, body metrics', writes: ['onboard'] },
  { name: 'plans',           desc: 'AI-generated nutrition/workout/recovery plans', writes: ['NutritionAgent', 'WorkoutAgent', 'RecoveryAgent'] },
  { name: 'health_logs',     desc: 'Food, workout, weight, sleep entries', writes: ['Every log action'] },
  { name: 'agent_decisions', desc: 'Full audit trail of every agent decision', writes: ['All 6 agents'] },
  { name: 'gamification',    desc: 'XP, level, streak, achievements', writes: ['award_xp', 'update_streak'] },
  { name: 'forecasts',       desc: '30-day weight projections (3 scenarios)', writes: ['ForecastingAgent'] },
]

export default function System() {
  const [apiStatus, setApiStatus] = useState<'checking' | 'ok' | 'error'>('checking')
  const [apiInfo, setApiInfo] = useState<any>(null)

  useEffect(() => {
    healthCheck().then(r => {
      setApiStatus('ok')
      setApiInfo(r.data)
    }).catch(() => setApiStatus('error'))
  }, [])

  return (
    <div className="space-y-6 pb-16">
      {/* Header */}
      <div className="bg-gradient-to-r from-gray-900 to-gray-950 border border-gray-800 rounded-2xl p-6">
        <div className="flex items-start justify-between">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="text-xs bg-green-500/20 text-green-400 border border-green-500/30 px-2 py-0.5 rounded-full font-medium">
                MongoDB Track
              </span>
              <span className="text-xs bg-purple-500/20 text-purple-400 border border-purple-500/30 px-2 py-0.5 rounded-full font-medium">
                Google Cloud Rapid Agent Hackathon 2026
              </span>
            </div>
            <h1 className="text-2xl font-black text-white">Adaptive HealthOS</h1>
            <p className="text-gray-400 mt-1">Multi-agent personal health operating system powered by Gemini 2.5 Flash + MongoDB Atlas</p>
          </div>
          <div className="text-right">
            <div className={`flex items-center gap-2 text-xs px-3 py-1.5 rounded-full border ${
              apiStatus === 'ok' ? 'bg-green-500/10 border-green-500/30 text-green-400' :
              apiStatus === 'error' ? 'bg-red-500/10 border-red-500/30 text-red-400' :
              'bg-gray-800 border-gray-700 text-gray-400'
            }`}>
              <span className={`w-1.5 h-1.5 rounded-full ${apiStatus === 'ok' ? 'bg-green-400 animate-pulse' : apiStatus === 'error' ? 'bg-red-400' : 'bg-gray-500'}`} />
              {apiStatus === 'ok' ? 'Backend live' : apiStatus === 'error' ? 'Backend offline' : 'Checking...'}
            </div>
            {apiInfo && (
              <p className="text-gray-600 text-xs mt-1">{apiInfo.gemini_model} · MongoDB {apiInfo.mongodb}</p>
            )}
          </div>
        </div>

        {/* Rule compliance checklist */}
        <div className="mt-4 grid grid-cols-2 md:grid-cols-3 gap-2">
          {[
            { rule: 'Uses Gemini (Google AI)', met: true },
            { rule: 'Google Cloud ADK', met: true },
            { rule: 'MongoDB Atlas MCP partner', met: true },
            { rule: 'Web application', met: true },
            { rule: 'New project (built June 2026)', met: true },
            { rule: 'Functional & deployed', met: true },
          ].map(({ rule, met }) => (
            <div key={rule} className={`flex items-center gap-2 text-xs px-2.5 py-1.5 rounded-lg ${met ? 'bg-green-500/5 text-green-400' : 'bg-red-500/5 text-red-400'}`}>
              <span>{met ? '✓' : '✗'}</span>
              <span>{rule}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Judging criteria */}
      <div>
        <h2 className="text-white font-bold text-lg mb-3">Judging Criteria Alignment</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {JUDGING_CRITERIA.map(c => (
            <div key={c.title} className={`border rounded-xl p-4 ${c.color}`}>
              <div className="flex items-center justify-between mb-3">
                <h3 className={`font-bold text-sm ${c.titleColor}`}>{c.title}</h3>
                <span className={`text-xs font-bold ${c.titleColor} bg-gray-900 px-2 py-0.5 rounded-full`}>{c.score}</span>
              </div>
              <div className="space-y-2">
                {c.items.map(item => (
                  <div key={item.label} className="flex items-start gap-2">
                    <span className="text-base leading-none mt-0.5">{item.icon}</span>
                    <div>
                      <span className="text-gray-500 text-xs">{item.label}: </span>
                      <span className="text-gray-300 text-xs">{item.value}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Agent architecture */}
      <div>
        <h2 className="text-white font-bold text-lg mb-3">6-Agent Architecture</h2>
        <div className="space-y-2">
          {AGENTS.map(a => (
            <div key={a.name} className="bg-gray-900 border border-gray-800 rounded-xl p-3">
              <div className="flex items-start justify-between gap-3">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <span className={`text-sm font-bold ${a.color}`}>{a.name}</span>
                    <span className="text-xs text-gray-600 bg-gray-800 px-2 py-0.5 rounded-full">triggers on: {a.trigger}</span>
                  </div>
                  <p className="text-gray-400 text-xs mb-2">{a.role}</p>
                  <div className="flex flex-wrap gap-1">
                    {a.tools.map(t => (
                      <span key={t} className="text-xs bg-gray-800 text-gray-500 px-1.5 py-0.5 rounded font-mono">
                        {t}()
                      </span>
                    ))}
                  </div>
                </div>
                <div className="flex items-center gap-1 shrink-0">
                  <span className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse" />
                  <span className="text-xs text-green-400">Active</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* MongoDB Atlas integration */}
      <div>
        <div className="flex items-center gap-2 mb-3">
          <h2 className="text-white font-bold text-lg">MongoDB Atlas Integration</h2>
          <span className="text-xs bg-green-500/10 border border-green-500/20 text-green-400 px-2 py-0.5 rounded-full">Partner MCP Track</span>
        </div>
        <div className="bg-gray-900 border border-gray-800 rounded-xl p-4 mb-3">
          <p className="text-gray-400 text-sm mb-3">
            All agent state, decisions, and user data flow through MongoDB Atlas. Each agent uses <span className="text-green-400 font-mono">FunctionTool</span> wrappers
            that map to dedicated Atlas collections — making MongoDB the persistent memory layer of the entire multi-agent system.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
            {MONGODB_COLLECTIONS.map(col => (
              <div key={col.name} className="bg-gray-800 rounded-lg p-2.5">
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-green-400 font-mono text-xs font-bold">{col.name}</span>
                </div>
                <p className="text-gray-500 text-xs">{col.desc}</p>
                <p className="text-gray-600 text-xs mt-1">Written by: {col.writes.join(', ')}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Tech stack */}
      <div>
        <h2 className="text-white font-bold text-lg mb-3">Full Tech Stack</h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          {[
            { layer: 'AI Model', tech: 'Gemini 2.5 Flash', via: 'Vertex AI', color: 'text-purple-400', bg: 'bg-purple-500/5 border-purple-500/20' },
            { layer: 'Agent SDK', tech: 'Google Cloud ADK', via: 'google-adk 1.34+', color: 'text-blue-400', bg: 'bg-blue-500/5 border-blue-500/20' },
            { layer: 'Database', tech: 'MongoDB Atlas', via: 'Motor async driver', color: 'text-green-400', bg: 'bg-green-500/5 border-green-500/20' },
            { layer: 'Backend', tech: 'FastAPI', via: 'Python 3.11 + uvicorn', color: 'text-yellow-400', bg: 'bg-yellow-500/5 border-yellow-500/20' },
            { layer: 'Frontend', tech: 'React 18 + Vite', via: 'TypeScript + Tailwind', color: 'text-cyan-400', bg: 'bg-cyan-500/5 border-cyan-500/20' },
            { layer: 'Frontend Deploy', tech: 'Vercel', via: 'CDN, global edge', color: 'text-white', bg: 'bg-gray-800 border-gray-700' },
            { layer: 'Backend Deploy', tech: 'Railway', via: 'Docker, auto-scale', color: 'text-orange-400', bg: 'bg-orange-500/5 border-orange-500/20' },
            { layer: 'Real-time', tech: 'WebSocket', via: 'FastAPI WS + polling', color: 'text-pink-400', bg: 'bg-pink-500/5 border-pink-500/20' },
          ].map(s => (
            <div key={s.layer} className={`border rounded-xl p-3 ${s.bg}`}>
              <p className="text-gray-600 text-xs mb-1">{s.layer}</p>
              <p className={`font-bold text-sm ${s.color}`}>{s.tech}</p>
              <p className="text-gray-500 text-xs">{s.via}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Fine print */}
      <div className="border border-gray-800 rounded-xl p-4 bg-gray-900/50">
        <p className="text-gray-600 text-xs text-center leading-relaxed">
          Adaptive HealthOS is powered by Gemini 2.5 Flash (Google Cloud AI). AI-generated plans and responses may contain errors or inaccuracies.
          This application is not a substitute for professional medical or nutritional advice. Always consult a qualified healthcare professional
          before making changes to your diet, exercise, or health regimen. Built for the Google Cloud Rapid Agent Hackathon 2026.
        </p>
      </div>
    </div>
  )
}
