import { useEffect, useState } from 'react'
import { healthCheck } from '../api/client'

const JUDGING_CRITERIA = [
  {
    score: '25pts', title: 'Technological Implementation',
    color: 'border-purple-200 bg-purple-50', titleColor: 'text-purple-700', scoreColor: 'bg-purple-100 text-purple-700',
    items: [
      { label: 'Google Cloud AI',  value: 'Gemini 2.5 Flash via Vertex AI',                              icon: '🧠' },
      { label: 'Agent Framework',  value: 'Google Cloud ADK (google-adk 1.34+)',                         icon: '⚙️' },
      { label: 'Partner MCP',      value: 'MongoDB Atlas — all state persisted via tool calls',          icon: '🍃' },
      { label: 'Agent Behavior',   value: '6 specialized agents with real tool use, planning & memory',  icon: '🤖' },
    ],
  },
  {
    score: '25pts', title: 'Design',
    color: 'border-blue-200 bg-blue-50', titleColor: 'text-blue-700', scoreColor: 'bg-blue-100 text-blue-700',
    items: [
      { label: 'UX',              value: 'Clean light-mode health dashboard, fully responsive',     icon: '🎨' },
      { label: 'Demo Flow',       value: 'One-click demo account loads full data instantly',        icon: '▶️' },
      { label: 'Agent Visibility',value: 'Live Agent Activity panel shows every agent decision',   icon: '📡' },
      { label: 'Data Viz',        value: 'Recharts weight trend, forecast scenarios, XP progress', icon: '📊' },
    ],
  },
  {
    score: '25pts', title: 'Potential Impact',
    color: 'border-emerald-200 bg-emerald-50', titleColor: 'text-emerald-700', scoreColor: 'bg-emerald-100 text-emerald-700',
    items: [
      { label: 'Problem',       value: "Generic fitness apps don't adapt — ours does, autonomously", icon: '🎯' },
      { label: 'Real-world use',value: 'Logs meals/workouts/sleep → agents update plans in <3s',    icon: '⚡' },
      { label: 'Scalability',   value: 'MongoDB Atlas scales to millions; agents are stateless',    icon: '📈' },
      { label: 'Personalization',value: 'Every plan is generated by Gemini from your actual data',  icon: '👤' },
    ],
  },
  {
    score: '25pts', title: 'Quality of Idea',
    color: 'border-amber-200 bg-amber-50', titleColor: 'text-amber-700', scoreColor: 'bg-amber-100 text-amber-700',
    items: [
      { label: 'Novelty',            value: 'First AI health OS with multi-agent plan adaptation',        icon: '✨' },
      { label: 'Agentic (not chat)', value: 'Agents plan → execute → store → notify autonomously',       icon: '🧩' },
      { label: 'MongoDB as memory',  value: 'Agent decisions, plans, logs all persist in Atlas',         icon: '💾' },
      { label: 'Wow factor',         value: 'Log poor sleep → RecoveryAgent cuts workout intensity live', icon: '🔥' },
    ],
  },
]

const AGENTS = [
  { name: 'OrchestratorAgent',     color: 'text-purple-600', bg: 'bg-purple-50 border-purple-100',  role: 'Routes user intent to specialist agents',            tools: ['classify_intent', 'route_to_agent'], trigger: 'Every chat message' },
  { name: 'NutritionAgent',        color: 'text-emerald-600', bg: 'bg-emerald-50 border-emerald-100', role: 'Analyzes food logs, adapts calorie targets',         tools: ['get_active_plan', 'create_plan', 'get_daily_nutrition_totals', 'log_agent_decision', 'award_xp'], trigger: 'Food log' },
  { name: 'WorkoutAgent',          color: 'text-blue-600',   bg: 'bg-blue-50 border-blue-100',       role: 'Tracks workout consistency, adjusts intensity',       tools: ['get_active_plan', 'create_plan', 'get_recent_logs', 'log_agent_decision', 'award_xp'], trigger: 'Workout log' },
  { name: 'RecoveryAgent',         color: 'text-amber-600',  bg: 'bg-amber-50 border-amber-100',     role: 'Analyzes sleep, reduces workout intensity if needed', tools: ['get_recent_logs', 'get_active_plan', 'create_plan', 'log_agent_decision'], trigger: 'Sleep log' },
  { name: 'ProgressAnalysisAgent', color: 'text-pink-600',   bg: 'bg-pink-50 border-pink-100',       role: 'Weight trend analysis, goal % tracking',             tools: ['get_user', 'get_recent_logs', 'save_forecast', 'log_agent_decision'], trigger: 'Weight log' },
  { name: 'ForecastingAgent',      color: 'text-cyan-600',   bg: 'bg-cyan-50 border-cyan-100',       role: '30-day weight forecast, 3 scenarios',                tools: ['get_user', 'get_recent_logs', 'save_forecast', 'log_agent_decision'], trigger: 'Progress check' },
]

const MONGODB_COLLECTIONS = [
  { name: 'users',           desc: 'Profile, goals, body metrics',                       writes: ['onboard'] },
  { name: 'plans',           desc: 'AI-generated nutrition/workout/recovery plans',      writes: ['NutritionAgent', 'WorkoutAgent', 'RecoveryAgent'] },
  { name: 'health_logs',     desc: 'Food, workout, weight, sleep entries',               writes: ['Every log action'] },
  { name: 'agent_decisions', desc: 'Full audit trail of every agent decision',           writes: ['All 6 agents'] },
  { name: 'gamification',    desc: 'XP, level, streak, achievements',                   writes: ['award_xp', 'update_streak'] },
  { name: 'forecasts',       desc: '30-day weight projections (3 scenarios)',            writes: ['ForecastingAgent'] },
]

export default function System() {
  const [apiStatus, setApiStatus] = useState<'checking' | 'ok' | 'error'>('checking')
  const [apiInfo, setApiInfo] = useState<any>(null)

  useEffect(() => {
    healthCheck().then(r => { setApiStatus('ok'); setApiInfo(r.data) }).catch(() => setApiStatus('error'))
  }, [])

  return (
    <div className="space-y-6 pb-16">
      {/* Header */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm">
        <div className="flex items-start justify-between">
          <div>
            <div className="flex items-center gap-2 mb-2 flex-wrap">
              <span className="text-xs bg-emerald-100 text-emerald-700 border border-emerald-200 px-2 py-0.5 rounded-full font-medium">MongoDB Track</span>
              <span className="text-xs bg-purple-100 text-purple-700 border border-purple-200 px-2 py-0.5 rounded-full font-medium">Google Cloud Rapid Agent Hackathon 2026</span>
            </div>
            <h1 className="text-2xl font-black text-slate-900">Adaptive HealthOS</h1>
            <p className="text-slate-500 mt-1 text-sm">Multi-agent personal health OS powered by Gemini 2.5 Flash + MongoDB Atlas</p>
          </div>
          <div className="text-right shrink-0 ml-4">
            <div className={`flex items-center gap-2 text-xs px-3 py-1.5 rounded-full border ${
              apiStatus === 'ok'       ? 'bg-emerald-50 border-emerald-200 text-emerald-700' :
              apiStatus === 'error'    ? 'bg-red-50 border-red-200 text-red-600' :
                                         'bg-slate-100 border-slate-200 text-slate-500'
            }`}>
              <span className={`w-1.5 h-1.5 rounded-full ${apiStatus === 'ok' ? 'bg-emerald-500 animate-pulse' : apiStatus === 'error' ? 'bg-red-500' : 'bg-slate-400'}`} />
              {apiStatus === 'ok' ? 'Backend live' : apiStatus === 'error' ? 'Backend offline' : 'Checking...'}
            </div>
            {apiInfo && <p className="text-slate-400 text-xs mt-1">{apiInfo.gemini_model} · MongoDB {apiInfo.mongodb}</p>}
          </div>
        </div>

        {/* Compliance checklist */}
        <div className="mt-4 grid grid-cols-2 md:grid-cols-3 gap-2">
          {[
            'Uses Gemini (Google AI)', 'Google Cloud ADK', 'MongoDB Atlas MCP partner',
            'Web application', 'New project (built June 2026)', 'Functional & deployed',
          ].map(rule => (
            <div key={rule} className="flex items-center gap-2 text-xs bg-emerald-50 border border-emerald-200 text-emerald-700 px-2.5 py-1.5 rounded-lg">
              <span>✓</span><span>{rule}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Judging criteria */}
      <div>
        <h2 className="text-slate-900 font-bold text-lg mb-3">Judging Criteria Alignment</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {JUDGING_CRITERIA.map(c => (
            <div key={c.title} className={`border rounded-xl p-4 ${c.color}`}>
              <div className="flex items-center justify-between mb-3">
                <h3 className={`font-bold text-sm ${c.titleColor}`}>{c.title}</h3>
                <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${c.scoreColor}`}>{c.score}</span>
              </div>
              <div className="space-y-2">
                {c.items.map(item => (
                  <div key={item.label} className="flex items-start gap-2">
                    <span className="text-base leading-none mt-0.5">{item.icon}</span>
                    <div>
                      <span className="text-slate-500 text-xs font-medium">{item.label}: </span>
                      <span className="text-slate-700 text-xs">{item.value}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Agent architecture */}
      <div>
        <h2 className="text-slate-900 font-bold text-lg mb-3">6-Agent Architecture</h2>
        <div className="space-y-2">
          {AGENTS.map(a => (
            <div key={a.name} className={`border rounded-xl p-3.5 ${a.bg}`}>
              <div className="flex items-start justify-between gap-3">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1 flex-wrap">
                    <span className={`text-sm font-bold ${a.color}`}>{a.name}</span>
                    <span className="text-xs text-slate-500 bg-white border border-slate-200 px-2 py-0.5 rounded-full">triggers on: {a.trigger}</span>
                  </div>
                  <p className="text-slate-600 text-xs mb-2">{a.role}</p>
                  <div className="flex flex-wrap gap-1">
                    {a.tools.map(t => (
                      <span key={t} className="text-xs bg-white text-slate-600 px-1.5 py-0.5 rounded border border-slate-200 font-mono shadow-sm">
                        {t}()
                      </span>
                    ))}
                  </div>
                </div>
                <div className="flex items-center gap-1 shrink-0">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
                  <span className="text-xs text-emerald-600 font-medium">Active</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* MongoDB Atlas */}
      <div>
        <div className="flex items-center gap-2 mb-3">
          <h2 className="text-slate-900 font-bold text-lg">MongoDB Atlas Integration</h2>
          <span className="text-xs bg-emerald-50 border border-emerald-200 text-emerald-700 px-2 py-0.5 rounded-full font-medium">Partner MCP Track</span>
        </div>
        <div className="bg-white border border-slate-200 rounded-xl p-4 mb-3 shadow-sm">
          <p className="text-slate-600 text-sm mb-3">
            All agent state, decisions, and user data flow through MongoDB Atlas. Each agent uses <span className="text-emerald-700 font-mono font-semibold">FunctionTool</span> wrappers
            that map to dedicated Atlas collections — making MongoDB the persistent memory layer of the entire multi-agent system.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
            {MONGODB_COLLECTIONS.map(col => (
              <div key={col.name} className="bg-slate-50 border border-slate-200 rounded-lg p-3">
                <span className="text-emerald-700 font-mono text-xs font-bold">{col.name}</span>
                <p className="text-slate-500 text-xs mt-0.5">{col.desc}</p>
                <p className="text-slate-400 text-xs mt-1">Written by: {col.writes.join(', ')}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Tech stack */}
      <div>
        <h2 className="text-slate-900 font-bold text-lg mb-3">Full Tech Stack</h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          {[
            { layer: 'AI Model',        tech: 'Gemini 2.5 Flash',   via: 'Vertex AI',           color: 'text-purple-700', bg: 'bg-purple-50 border-purple-100' },
            { layer: 'Agent SDK',       tech: 'Google Cloud ADK',   via: 'google-adk 1.34+',    color: 'text-blue-700',   bg: 'bg-blue-50 border-blue-100'     },
            { layer: 'Database',        tech: 'MongoDB Atlas',      via: 'Motor async driver',  color: 'text-emerald-700',bg: 'bg-emerald-50 border-emerald-100'},
            { layer: 'Backend',         tech: 'FastAPI',            via: 'Python 3.11 + uvicorn',color: 'text-amber-700', bg: 'bg-amber-50 border-amber-100'   },
            { layer: 'Frontend',        tech: 'React 18 + Vite',    via: 'TypeScript + Tailwind',color: 'text-cyan-700',  bg: 'bg-cyan-50 border-cyan-100'     },
            { layer: 'Frontend Deploy', tech: 'Vercel',             via: 'CDN, global edge',    color: 'text-slate-700',  bg: 'bg-slate-50 border-slate-200'   },
            { layer: 'Backend Deploy',  tech: 'Railway',            via: 'Docker, auto-scale',  color: 'text-orange-700', bg: 'bg-orange-50 border-orange-100' },
            { layer: 'Real-time',       tech: 'WebSocket',          via: 'FastAPI WS + polling',color: 'text-pink-700',   bg: 'bg-pink-50 border-pink-100'     },
          ].map(s => (
            <div key={s.layer} className={`border rounded-xl p-3 ${s.bg}`}>
              <p className="text-slate-400 text-xs mb-1">{s.layer}</p>
              <p className={`font-bold text-sm ${s.color}`}>{s.tech}</p>
              <p className="text-slate-500 text-xs">{s.via}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Fine print */}
      <div className="border border-slate-200 rounded-xl p-4 bg-slate-50">
        <p className="text-slate-400 text-xs text-center leading-relaxed">
          Adaptive HealthOS is powered by Gemini 2.5 Flash (Google Cloud AI). AI-generated plans and responses may contain errors or inaccuracies.
          This application is not a substitute for professional medical or nutritional advice. Always consult a qualified healthcare professional
          before making changes to your diet, exercise, or health regimen. Built for the Google Cloud Rapid Agent Hackathon 2026.
        </p>
      </div>
    </div>
  )
}
